spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toolsrental_0328_db?serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: UTC

application:
  security:
    jwt: ## # toolrentaldemoapplicationsecretkey https://www.base64encode.org/
      secret-key: dG9vbHJlbnRhbGRlbW9hcHBsaWNhdGlvbnNlY3JldGtleQ==
      expiration: 86400000 #(In Milliseconds)  #86400000 # a day

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
